#! /usr/bin/env bash

echo "Building site..."
JEKYLL_ENV=production bundle exec jekyll build -d ../ayaankazerouni.github.io/

echo "Deploying site..."
cd ../ayaankazerouni.github.io
git add --all
git commit --amend -m "Build."
git push -f origin master
cd -
