#! /usr/bin/env bash

echo "Building site..."
JEKYLL_ENV=production bundle exec jekyll build -d docs/

# echo "Deploying site..."
# rsync -r -e ssh ./_site/ ayaan@rlogin.cs.vt.edu:/home/grads/ayaan/WWW/people.cs.vt.edu/
